[build-system]
requires = ["setuptools>=45"]
build-backend = "setuptools.build_meta"


[project]
name = "BeAMF" 
version = "1.0.2"
requires-python = ">=3.7"
dependencies = [
				 "numpy",
				 "scipy",
				 "netCDF4"
				]

[project.scripts]
beamf = "BeAMF:cml"
